# Generated by Django 5.2.7 on 2025-11-17 18:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "schema_json",
                    models.JSONField(
                        default=dict,
                        help_text="Complete form schema with fields and logic",
                    ),
                ),
                (
                    "settings_json",
                    models.JSONField(
                        default=dict,
                        help_text="Integrations, privacy, and other settings",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="Version number for tracking changes"
                    ),
                ),
                ("views_count", models.IntegerField(default=0)),
                ("submissions_count", models.IntegerField(default=0)),
                (
                    "completion_count",
                    models.IntegerField(
                        default=0, help_text="Submissions marked as complete"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "forms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("photography", "Photography"),
                            ("health", "Health & Wellness"),
                            ("fitness", "Fitness & Gym"),
                            ("real_estate", "Real Estate"),
                            ("consulting", "Consulting"),
                            ("events", "Events & Catering"),
                            ("general", "General"),
                        ],
                        max_length=50,
                    ),
                ),
                ("schema_json", models.JSONField(help_text="Template form schema")),
                ("thumbnail_url", models.URLField(blank=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "form_templates",
                "ordering": ["-is_featured", "-usage_count"],
            },
        ),
        migrations.CreateModel(
            name="FormVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.IntegerField()),
                ("schema_json", models.JSONField()),
                ("settings_json", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "form_versions",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="NotificationConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("on_submit", "On Submission"),
                            ("on_payment", "On Payment Success"),
                            ("on_failure", "On Payment Failure"),
                        ],
                        default="on_submit",
                        max_length=20,
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        help_text="Email address, phone number, or webhook URL",
                        max_length=500,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=500)),
                (
                    "template",
                    models.TextField(
                        help_text="Email/SMS template with {{field_name}} placeholders"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "notification_configs",
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payload_json",
                    models.JSONField(help_text="Complete form submission data"),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True, help_text="Stripe Payment Intent ID", max_length=255
                    ),
                ),
                (
                    "payment_amount",
                    models.IntegerField(
                        blank=True, help_text="Payment amount in cents", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "submissions",
                "ordering": ["-created_at"],
            },
        ),
    ]
