# Generated by Django 5.2.7 on 2025-11-17 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forms", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forms",
                to="users.team",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="formversion",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="forms.form",
            ),
        ),
        migrations.AddField(
            model_name="notificationconfig",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="forms.form",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="forms.form",
            ),
        ),
        migrations.AddIndex(
            model_name="form",
            index=models.Index(fields=["slug"], name="forms_slug_8b125c_idx"),
        ),
        migrations.AddIndex(
            model_name="form",
            index=models.Index(
                fields=["user", "-created_at"], name="forms_user_id_830300_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="formversion",
            unique_together={("form", "version")},
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["form", "-created_at"], name="submissions_form_id_75516e_idx"
            ),
        ),
    ]
