# Generated by Django 5.2.7 on 2026-01-01 17:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0007_emerging_features"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("icon", models.URLField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("legendary", "Legendary"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "points_reward",
                    models.IntegerField(
                        default=50,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("criteria", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "achievement",
                "ordering": ["difficulty", "name"],
            },
        ),
        migrations.CreateModel(
            name="InteractiveFormAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "form_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "total_views",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_submissions",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "completion_rate",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "average_completion_time",
                    models.IntegerField(default=0, help_text="in seconds"),
                ),
                (
                    "bounce_rate",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "conversion_rate",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "interactive_form_analytics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ARAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("model", "3D Model"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("animation", "Animation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="ar_assets/%Y/%m/%d/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="ar_assets/thumbnails/"
                    ),
                ),
                ("form_id", models.CharField(blank=True, max_length=100, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ar_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ar_asset",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ARPreview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("form_id", models.CharField(max_length=100)),
                ("rotation", models.JSONField(default=dict)),
                ("scale", models.JSONField(default=dict)),
                ("position", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="forms.arasset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ar_previews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ar_preview",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("form_id", models.CharField(blank=True, max_length=100, null=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_session",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="forms.chatsession",
                    ),
                ),
            ],
            options={
                "db_table": "chat_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("action", models.JSONField(default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="forms.chatsession",
                    ),
                ),
            ],
            options={
                "db_table": "chat_suggestion",
            },
        ),
        migrations.CreateModel(
            name="CollaborationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("form_id", models.CharField(db_index=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_users",
                    models.IntegerField(
                        default=50,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
            options={
                "db_table": "collaboration_session",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["form_id", "is_active"],
                        name="collaborati_form_id_0e1d1c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyStreak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "current_count",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_count",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("last_activity_date", models.DateField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_streak",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "daily_streak",
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("form_id", models.CharField(db_index=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True)),
                (
                    "completion_time",
                    models.IntegerField(blank=True, help_text="in seconds", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "form_submission",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GamificationProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "total_points",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "experience",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("experience_to_next_level", models.IntegerField(default=1000)),
                (
                    "current_streak",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "longest_streak",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("last_activity_date", models.DateField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gamification_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gamification_profile",
                "ordering": ["-total_points", "-level"],
            },
        ),
        migrations.CreateModel(
            name="GestureEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("form_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "gesture_type",
                    models.CharField(
                        choices=[
                            ("swipe", "Swipe"),
                            ("pinch", "Pinch"),
                            ("tap", "Tap"),
                            ("long_press", "Long Press"),
                            ("rotate", "Rotate"),
                        ],
                        max_length=50,
                    ),
                ),
                ("direction", models.CharField(blank=True, max_length=20, null=True)),
                ("coordinates", models.JSONField(default=dict)),
                ("action_triggered", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gesture_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gesture_event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GestureSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "sensitivity",
                    models.IntegerField(
                        default=5,
                        help_text="1-10 scale",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("gestures", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gesture_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gesture_settings",
            },
        ),
        migrations.CreateModel(
            name="InteractiveFieldAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("field_id", models.CharField(max_length=100)),
                ("field_label", models.CharField(max_length=200)),
                (
                    "views",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "interactions",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "drop_offs",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "average_time_spent",
                    models.IntegerField(default=0, help_text="in seconds"),
                ),
                (
                    "error_count",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "help_clicks",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "form_analytics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="forms.interactiveformanalytics",
                    ),
                ),
            ],
            options={
                "db_table": "interactive_field_analytics",
                "ordering": ["field_label"],
            },
        ),
        migrations.CreateModel(
            name="InteractiveAnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_date", models.DateField(db_index=True)),
                ("views", models.IntegerField(default=0)),
                ("submissions", models.IntegerField(default=0)),
                ("completion_rate", models.FloatField(default=0.0)),
                (
                    "form_analytics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="forms.interactiveformanalytics",
                    ),
                ),
            ],
            options={
                "db_table": "interactive_analytics_snapshot",
                "ordering": ["-period_date"],
            },
        ),
        migrations.CreateModel(
            name="InteractiveAnalyticsEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("form_id", models.CharField(db_index=True, max_length=100)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("view", "Form View"),
                            ("start", "Form Started"),
                            ("field_focus", "Field Focus"),
                            ("field_blur", "Field Blur"),
                            ("field_error", "Field Error"),
                            ("field_change", "Field Changed"),
                            ("help_click", "Help Clicked"),
                            ("submit", "Form Submit"),
                            ("abandon", "Form Abandoned"),
                        ],
                        max_length=50,
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                ("field_id", models.CharField(blank=True, max_length=100, null=True)),
                ("value", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form_analytics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="forms.interactiveformanalytics",
                    ),
                ),
            ],
            options={
                "db_table": "interactive_analytics_event",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="InteractiveWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("form_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("form_submit", "Form Submit"),
                            ("field_change", "Field Change"),
                            ("time", "Time-based"),
                            ("webhook", "Webhook"),
                            ("manual", "Manual"),
                        ],
                        max_length=50,
                    ),
                ),
                ("trigger_config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "interactive_workflow",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InteractiveWorkflowExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("trigger_data", models.JSONField(default=dict)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "execution_time",
                    models.IntegerField(
                        blank=True, help_text="in milliseconds", null=True
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="forms.interactiveworkflow",
                    ),
                ),
            ],
            options={
                "db_table": "interactive_workflow_execution",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="InteractiveWorkflowStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("email", "Send Email"),
                            ("sms", "Send SMS"),
                            ("slack", "Slack Notification"),
                            ("webhook", "Webhook Call"),
                            ("conditional", "Conditional Branch"),
                            ("delay", "Delay"),
                            ("transform", "Transform Data"),
                        ],
                        max_length=50,
                    ),
                ),
                ("action_config", models.JSONField(default=dict)),
                ("condition", models.JSONField(blank=True, null=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="forms.interactiveworkflow",
                    ),
                ),
            ],
            options={
                "db_table": "interactive_workflow_step",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="InteractiveWorkflowStepExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_executions",
                        to="forms.interactiveworkflowexecution",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forms.interactiveworkflowstep",
                    ),
                ),
            ],
            options={
                "db_table": "interactive_workflow_step_execution",
                "ordering": ["step__order"],
            },
        ),
        migrations.CreateModel(
            name="PointsLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(-1000)]
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("form_created", "Form Created"),
                            ("form_published", "Form Published"),
                            ("field_added", "Field Added"),
                            ("form_submitted", "Form Submitted"),
                            ("achievement", "Achievement Unlocked"),
                            ("daily_bonus", "Daily Bonus"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("form_id", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "points_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("field_id", models.CharField(max_length=100)),
                ("field_label", models.CharField(max_length=200)),
                ("value", models.TextField()),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="forms.formsubmission",
                    ),
                ),
            ],
            options={
                "db_table": "submission_field",
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forms.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_achievement",
                "ordering": ["-unlocked_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("color", models.CharField(default="#3498db", max_length=7)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "collaboration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="forms.collaborationsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_session",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="CursorPosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("x", models.FloatField(default=0)),
                ("y", models.FloatField(default=0)),
                ("field_id", models.CharField(blank=True, max_length=100, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cursor",
                        to="forms.usersession",
                    ),
                ),
            ],
            options={
                "db_table": "cursor_position",
            },
        ),
        migrations.CreateModel(
            name="CollaborationMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Message"),
                            ("system", "System Message"),
                            ("notification", "Notification"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "collaboration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="forms.collaborationsession",
                    ),
                ),
                (
                    "read_by",
                    models.ManyToManyField(
                        blank=True, related_name="read_messages", to="forms.usersession"
                    ),
                ),
                (
                    "user_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="forms.usersession",
                    ),
                ),
            ],
            options={
                "db_table": "collaboration_message",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="VoiceTranscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("form_id", models.CharField(blank=True, max_length=100, null=True)),
                ("field_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "audio_file",
                    models.FileField(upload_to="voice_transcriptions/%Y/%m/%d/"),
                ),
                ("text", models.TextField()),
                (
                    "confidence",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                ("language", models.CharField(default="en-US", max_length=10)),
                ("duration", models.IntegerField(help_text="in milliseconds")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_transcriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "voice_transcription",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("form_id", models.CharField(max_length=100)),
                (
                    "command_type",
                    models.CharField(
                        choices=[
                            ("add_field", "Add Field"),
                            ("delete_field", "Delete Field"),
                            ("rename_field", "Rename Field"),
                            ("change_type", "Change Type"),
                            ("submit", "Submit"),
                            ("clear", "Clear"),
                            ("undo", "Undo"),
                            ("redo", "Redo"),
                        ],
                        max_length=50,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("executed", models.BooleanField(default=False)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transcription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="forms.voicetranscription",
                    ),
                ),
            ],
            options={
                "db_table": "voice_command",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="arasset",
            index=models.Index(
                fields=["owner", "is_public"], name="ar_asset_owner_i_8f0efb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "is_active"], name="chat_sessio_user_id_5cf35d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="chat_messag_session_4940cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(
                fields=["form_id", "status"], name="form_submis_form_id_8e7b24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(
                fields=["user", "created_at"], name="form_submis_user_id_48bd19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gamificationprofile",
            index=models.Index(
                fields=["total_points"], name="gamificatio_total_p_e06524_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gamificationprofile",
            index=models.Index(fields=["level"], name="gamificatio_level_0af12a_idx"),
        ),
        migrations.AddIndex(
            model_name="gestureevent",
            index=models.Index(
                fields=["user", "created_at"], name="gesture_eve_user_id_2b0cf3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="interactivefieldanalytics",
            unique_together={("form_analytics", "field_id")},
        ),
        migrations.AlterUniqueTogether(
            name="interactiveanalyticssnapshot",
            unique_together={("form_analytics", "period", "period_date")},
        ),
        migrations.AddIndex(
            model_name="interactiveanalyticsevent",
            index=models.Index(
                fields=["form_id", "timestamp"], name="interactive_form_id_d95553_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interactiveanalyticsevent",
            index=models.Index(
                fields=["session_id"], name="interactive_session_e3ea68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interactiveworkflow",
            index=models.Index(
                fields=["owner", "status"], name="interactive_owner_i_a14354_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interactiveworkflow",
            index=models.Index(
                fields=["form_id"], name="interactive_form_id_d3cf3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interactiveworkflowexecution",
            index=models.Index(
                fields=["workflow", "status"], name="interactive_workflo_007bed_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="interactiveworkflowstep",
            unique_together={("workflow", "order")},
        ),
        migrations.AddIndex(
            model_name="pointslog",
            index=models.Index(
                fields=["user", "created_at"], name="points_log_user_id_480296_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submissionfield",
            unique_together={("submission", "field_id")},
        ),
        migrations.AlterUniqueTogether(
            name="userachievement",
            unique_together={("user", "achievement")},
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["collaboration", "user"], name="user_sessio_collabo_ab2bb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["last_activity"], name="user_sessio_last_ac_e10a79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationmessage",
            index=models.Index(
                fields=["collaboration", "timestamp"],
                name="collaborati_collabo_db82de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="voicetranscription",
            index=models.Index(
                fields=["form_id", "field_id"], name="voice_trans_form_id_486fb8_idx"
            ),
        ),
    ]
