# Generated by Django 5.2.7 on 2025-12-28 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0008_activitylog_autofilltemplate_brandguideline_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="webhooklog",
            new_name="webhook_log_webhook_ae7936_idx",
            old_name="webhook_log_webhook_60a3ab_idx",
        ),
        migrations.AlterField(
            model_name="abtest",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ab_tests_basic",
                to="forms.form",
            ),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent_records",
                to="forms.submission",
            ),
        ),
        migrations.AlterField(
            model_name="consenttracking",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent_tracking",
                to="forms.submission",
            ),
        ),
        migrations.AlterField(
            model_name="formabtest",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ab_tests_advanced",
                to="forms.form",
            ),
        ),
        migrations.AlterField(
            model_name="formintegration",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_integrations",
                to="forms.form",
            ),
        ),
        migrations.AlterField(
            model_name="formnotification",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="push_notifications",
                to="forms.form",
            ),
        ),
        migrations.AlterModelTable(
            name="webhooklog",
            table="webhook_logs_marketplace",
        ),
    ]
