# Generated by Django 6.0 on 2026-02-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0009_alter_enhancedformcomment_mentions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationalaiconfig",
            name="ai_provider",
            field=models.CharField(
                choices=[
                    ("groq", "Groq"),
                    ("openai", "OpenAI GPT-4"),
                    ("anthropic", "Anthropic Claude"),
                    ("google", "Google Gemini"),
                    ("custom", "Custom LLM"),
                ],
                default="openai",
                max_length=20,
            ),
        ),
    ]
